# Numpy

## Ejemplo de array en Numpy


<img style="text-align_left" src="../images/numpy/numpy_array_t.png" width=60% height=60% />

In [1]:
import numpy as np
array = np.arange(15).reshape(3,5) 
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Se puede ver como se ha creado una matriz donde están almacenados los números del 1 al 14. Esta matriz tiene unas dimensiones de 3 filas por 5 columnas.

In [2]:
array.shape #Número de filas y columnas.

(3, 5)

In [3]:
array.ndim #Dimesión de la matriz.

2

In [4]:
array.itemsize #Tamaño en bytes de los elementos del array.

8

In [5]:
type(array) #Tipo de la variable.

numpy.ndarray

## Creación de arrays

Los arrays en Numpy se pueden crear de muchas maneras, vamos a ver varios ejemplos de esto.

### Creación de arrays desde listas

In [6]:
import numpy as np
a = np.array([2, 3, 4]) #Creamos el array desde una lista de python.
a

array([2, 3, 4])

In [7]:
a.dtype #Imprimimos el tipo de los elementos del array.

dtype('int64')

In [8]:
import numpy as np
b = np.array([1.1, 1.2, 1.3]) #Otro ejemplo pero con floats.
b.dtype

dtype('float64')

### Creación mediante funciones

In [9]:
import numpy as np
np.zeros(2) #Creamos un array de 1x2 rellenado con ceros.

array([0., 0.])

In [10]:
np.ones(2) #Creamos un array de 1x2 rellenado con unos.

array([1., 1.])

In [11]:
np.ones((2,2)) #Creamos un array de 2x2 rellenado con unos.

array([[1., 1.],
       [1., 1.]])

In [12]:
np.empty(5) #Crea un array de 1x5 con contenido random.

array([ 1.  ,  2.75,  6.  , 10.75, 17.  ])

In [13]:
np.arange(6) #Crea un array de 1x6 desde el 0 al 5.

array([0, 1, 2, 3, 4, 5])

In [14]:
np.arange(2, 10, 3) #Crea un array de 1x3, desde el número 2 al 10, incrementando de 3 en 3 los números.

array([2, 5, 8])

In [15]:
np.linspace(0, 1, num=10) #Crea un array de 1x10 desde el 0 al 1.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [16]:
np.ones(2, dtype=np.int64) #También se puede indicar el tipo de los elementos del array.

array([1, 1])

## Añadir, eliminar y ordenar elementos

In [17]:
arr = np.random.randint(100, size=10)
arr

array([35, 47, 24, 51, 65, 74, 86, 90, 91, 75])

In [18]:
np.sort(arr) #Ordenamos los elementos del array.

array([24, 35, 47, 51, 65, 74, 75, 86, 90, 91])

In [19]:
a = np.random.randint(100, size=5)
b = np.random.randint(100, size=5)

In [20]:
np.concatenate((a, b)) #Creamos un nuevo array con los elementos de A y B.

array([59, 38, 11, 77, 46, 60, 74, 25, 43, 32])

In [21]:
x = np.array([[1, 2], [3, 4]]) 
y = np.array([[5, 6]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [22]:
np.concatenate((x, y), axis=0) #Concatenamos a nivel de filas.

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
arr = np.random.randint(100, size=10)
index = [3, 4, 5]
arr

array([ 6,  3, 11,  9, 35, 75, 87, 28,  6, 76])

In [24]:
np.delete(arr, index) #Eliminamos los elementos 3, 4 y 5 del array.

array([ 6,  3, 11, 87, 28,  6, 76])

## Remodelar un array

In [25]:
a = np.random.randint(100, size=12)
print(a)

[45 31 49 38  1 14 52  5  5 71  6 11]


In [26]:
a.reshape(3, 4) #Transformamos el array en una matriz de 3x4.

array([[45, 31, 49, 38],
       [ 1, 14, 52,  5],
       [ 5, 71,  6, 11]])

## Convertir array de una dimensión en un array de 2 dimensiones

In [27]:
a = np.random.randint(100, size=12)
a.shape

(12,)

In [28]:
a2 = a[np.newaxis, :] #Añadimos una nueva dimensión.
print(a2)
print(a2.shape)

[[89 98 15 86 86 58 56 63 68 60 84 23]]
(1, 12)


In [29]:
row_vector = a[np.newaxis, :] #Transformamos el array en una matriz de una sola fila y 12 columnas.
print(row_vector)
print(row_vector.shape)

[[89 98 15 86 86 58 56 63 68 60 84 23]]
(1, 12)


In [30]:
col_vector = a[:, np.newaxis] #Transformamos el array en una matriz de 12 filas y una columna.
print(col_vector)
print(col_vector.shape)


[[89]
 [98]
 [15]
 [86]
 [86]
 [58]
 [56]
 [63]
 [68]
 [60]
 [84]
 [23]]
(12, 1)


In [31]:
b = np.expand_dims(a, axis=1) #Expandimos el array añadiendo una nueva dimensión en la posición 1.
b.shape

(12, 1)

In [32]:
c = np.expand_dims(a, axis=0) #Expandimos el array añadiendo una nueva dimensión en la posición 0.
c.shape

(1, 12)

## Indexando y desplazando

In [33]:
data = np.array([13, 77, 77, 50, 62, 95])
data

array([13, 77, 77, 50, 62, 95])

In [34]:
data[1] #Obtenemos el elemento 1 del array.

77

In [35]:
data[0:2] #Obtenemos los elementos desde el 0 al 2, sin incluir este último.

array([13, 77])

In [36]:
data[1:] #Obtenemos todos los elementos desde el primero.

array([77, 77, 50, 62, 95])

In [37]:
data[-2:] #Obtenemos los dos últimos elementos.

array([62, 95])

<img style="text-align_left" src="../images/numpy/Slicing.png" width=50% height=50% />

In [38]:
a = np.random.randint(10, size=(3, 4))
a

array([[5, 7, 9, 4],
       [6, 7, 0, 5],
       [4, 3, 6, 6]])

In [39]:
a[a < 5] #Seleccionamos los elementos que son menores que 5.

array([4, 0, 4, 3])

In [40]:
a[a > 5] #Seleccionamos los elementos que son mayores que 5.

array([7, 9, 6, 7, 6, 6])

In [41]:
a[a%2==0] #Elementos que son divisibles por 2.

array([4, 6, 0, 4, 6, 6])

In [42]:
a[(a > 2) & (a < 7)] #Podemos concatenar elementos mediante el operador & (and) y \ (or).

array([5, 4, 6, 5, 4, 3, 6, 6])

In [43]:
(a > 5) | (a == 5) #Imprimimos una matriz de booleanos con los valores en función de las condiciones establecidas.

array([[ True,  True,  True, False],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [44]:
b = np.nonzero(a < 5) #Obtenemos los índices de los elementos que cumplen con la condición. 
#El primer array muestra los índices de las filas.
#El segundo, los índices de las columnas.

b

(array([0, 1, 2, 2]), array([3, 2, 0, 1]))

In [45]:
list_of_coordinates = list(zip(b[0], b[1])) #Visto de otra manera.
for coord in list_of_coordinates:
    print(coord)

(0, 3)
(1, 2)
(2, 0)
(2, 1)


In [46]:
np.nonzero(a == 42) #Si no existe ningún elemento que cumpla con la condición, devuelve los arrays vacios.

(array([], dtype=int64), array([], dtype=int64))

## Crear array desde datos existentes

In [47]:
a = np.random.randint(100, size=10)

In [48]:
arr1 = a[3:8] #Creamos un array desde el elemento 3 al 8.
arr1

array([83,  5, 27, 66, 51])

In [49]:
a1 = np.random.randint(10, size=(2, 2))
a1

array([[0, 9],
       [9, 3]])

In [50]:
a2 = np.random.randint(10, size=(2, 2))
a2

array([[7, 6],
       [0, 5]])

In [51]:
np.vstack((a1, a2)) #Añadimos uno al otro de forma vertical.

array([[0, 9],
       [9, 3],
       [7, 6],
       [0, 5]])

In [52]:
np.hstack((a1, a2)) #Lo mismo pero de forma horizontal.

array([[0, 9, 7, 6],
       [9, 3, 0, 5]])

In [53]:
a = np.random.randint(100, size=27).reshape(3,9)
a

array([[87, 97,  4,  4, 42, 24, 31, 47, 57],
       [76, 56,  2, 76,  7, 51, 69, 75, 42],
       [21, 50, 66, 76, 89, 80, 66, 98, 73]])

In [54]:
np.hsplit(a, 3) #Dividimos el array en elementos de 3.

[array([[87, 97,  4],
        [76, 56,  2],
        [21, 50, 66]]),
 array([[ 4, 42, 24],
        [76,  7, 51],
        [76, 89, 80]]),
 array([[31, 47, 57],
        [69, 75, 42],
        [66, 98, 73]])]

In [55]:
np.hsplit(a, (2,2)) #Dividimos los elementos en matrices de 2x2.

[array([[87, 97],
        [76, 56],
        [21, 50]]),
 array([], shape=(3, 0), dtype=int64),
 array([[ 4,  4, 42, 24, 31, 47, 57],
        [ 2, 76,  7, 51, 69, 75, 42],
        [66, 76, 89, 80, 66, 98, 73]])]

In [56]:
a = np.random.randint(100, size=12).reshape(3,4)
a

array([[72,  9, 59, 21],
       [71, 24, 20, 86],
       [12, 76, 66, 52]])

In [57]:
b1 = a[0, :] #Seleccionamos la primera fila de la matriz creada antes.
b1

array([72,  9, 59, 21])

In [58]:
b1[0] = 0 #Modificamos la primera posición del vector por un 0.
b1

array([ 0,  9, 59, 21])

In [59]:
a #Como son referencias a memoria, se ha modificado tanto en b1 como en a.

array([[ 0,  9, 59, 21],
       [71, 24, 20, 86],
       [12, 76, 66, 52]])

## Operaciones básicas de arrays

In [60]:
data = np.array([17,73]) #Generamos el array.
data

array([17, 73])

In [61]:
ones = np.ones(2,dtype=int) #Generamos un array de unos.
ones

array([1, 1])

In [62]:
data + ones #Sumamos estos arrays.

array([18, 74])

<img style="text-align_left" src="../images/numpy/suma.png" width=25% height=25% />

In [63]:
data - ones #Restamos estos arrays.

array([16, 72])

In [64]:
data * data #Multiplicamos estos arrays.

array([ 289, 5329])

In [65]:
data / data #Dividimos estos arrays.

array([1., 1.])

<img style="text-align_left" src="../images/numpy/operaciones.png" width=80% height=80% />

In [66]:
data.sum() #Nos devuelva la suma de todos los elementos del array.

90

In [67]:
data = np.random.randint(100, size=(2,2))
data.sum(axis=0) #Sumamos las filas.

array([114, 127])

In [68]:
data.sum(axis=1) #Sumamos las columnas.

array([116, 125])

## Operaciones de arrays y números (Broadcasting)

In [69]:
data = np.array([17,73])
data * 1.5 #Numpy entiende que la multiplicación es como si se tuviera un array 
#donde todas las celdas tienen el mismo número

array([ 25.5, 109.5])

<img style="text-align_left" src="../images/numpy/op_num.png" width=45% height=45% />

## Otras operaciones de arrays

In [70]:
data.max() #Obtiene el elemento más grande del array.

73

In [71]:
data.min() # Obtiene el elemento más pequeño del array.

17

## Creando matrices

In [72]:
data = np.array([[7, 22], [15, 46], [9, 11]]) #Creamos una matriz desde varias listas de python.
data

array([[ 7, 22],
       [15, 46],
       [ 9, 11]])

In [73]:
data[0,1] #Seleccionamos el elemento perteneciente a la fila 0 y columna 1.

22

In [74]:
data[1:3] #Seleccionamos la fila 2 y 3

array([[15, 46],
       [ 9, 11]])

In [75]:
data[0:2, 0] #Seleccionamos la primera columna de las dos primeras filas.

array([ 7, 15])

<img style="text-align_left" src="../images/numpy/matrix.png" width=55% height=55% />

In [76]:
data.max() #Obtenemos el elemento más grande de la matriz.

46

In [77]:
data.min() #Obtenemos el elemento más pequeño de la matriz.

7

In [78]:
data.sum()  #Obtenemos la suma de los elementos de la matriz.

110

In [79]:
data.max(axis=0) #Obtenemos el elemento más grande de cada columna.

array([15, 46])

In [80]:
data.max(axis=1)  #Obtenemos el elemento más grande de cada fila.

array([22, 46, 11])

<img style="text-align_left" src="../images/numpy/matrix_max_min.png" width=45% height=45% />

In [81]:
data = np.array([[7, 22], [15, 46]])
data

array([[ 7, 22],
       [15, 46]])

In [82]:
ones = np.array([[1, 1], [1, 1]])
ones

array([[1, 1],
       [1, 1]])

In [83]:
data + ones #Suma de dos matrices.

array([[ 8, 23],
       [16, 47]])

<img style="text-align_left" src="../images/numpy/matrix_sum_ones.png" width=45% height=45% />

In [84]:
data = np.array([[7, 22], [15, 46], [9, 11]])
data

array([[ 7, 22],
       [15, 46],
       [ 9, 11]])

In [85]:
ones_row = np.array([[1, 1]])

In [86]:
data + ones_row #Suma de una matriz y un vector.

array([[ 8, 23],
       [16, 47],
       [10, 12]])

<img style="text-align_left" src="../images/numpy/matrix_sum_one_row.png" width=80% height=80% />

In [87]:
np.ones(3) #Creamos una matriz de 3x1 relleno con 1.

array([1., 1., 1.])

In [88]:
np.zeros(3) #Creamos una matriz de 3x1 relleno con 0.

array([0., 0., 0.])

In [89]:
np.random.random(3)  #Creamos una matriz de 3x1 relleno con números aleatorios.

array([0.33025691, 0.94855235, 0.18669193])

In [90]:
np.ones((3, 2)) #Matriz de 3x2 rellena de unos.

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [91]:
np.zeros((3, 2))  #Matriz de 3x2 rellena de ceros.

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [92]:
np.random.random((3,2)) #Matriz de 3x2 rellena con números aleatorios.

array([[0.14639973, 0.65264294],
       [0.13989044, 0.71776773],
       [0.39705557, 0.77064471]])

## Generando números aleatorios

In [93]:
rng = np.random.default_rng()
rng.integers(5, size=(2, 4)) #Creamos una matriz de 2x4 de números enterios con un valor máximo de 5.

array([[3, 2, 1, 0],
       [4, 2, 2, 4]])

## Obtener elementos únicos y contar elementos

In [94]:
a = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 6])

In [95]:
np.unique(a) #Obtenemos los elementos únicos.

array([1, 2, 3, 4, 5, 6])

In [96]:
np.unique(a, return_index=True) #OBtenemos los elementos únicos y sus índices.

(array([1, 2, 3, 4, 5, 6]), array([0, 1, 2, 3, 4, 9]))

In [97]:
np.unique(a, return_counts=True) #Imprime cuantas veces está cada elemento único.

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 2, 1, 1]))

In [98]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [99]:
np.unique(matrix)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [100]:
np.unique(matrix, axis=0) #Obtiene las filas con valores únicos.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
np.unique(matrix, axis=0, return_counts=True, return_index=True) #Obtiene las filas con valores únicoas
#las ocurrencias y los índices de estas.

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([0, 1, 2]),
 array([2, 1, 1]))

 ## Transformando y cambiando el tamaño de una matriz

In [102]:
matrix = np.random.randint(100, size=(3,2))
matrix

array([[17, 13],
       [37, 93],
       [ 4, 40]])

In [103]:
matrix.reshape(2, 3) #Transformamos la matriz en una nueva de 2 filas y tres columnas.

array([[17, 13, 37],
       [93,  4, 40]])

In [104]:
matrix.transpose() #Creamos la matriz transpuesta. 

array([[17, 37,  4],
       [13, 93, 40]])

In [105]:
matrix.T #Otra manera de hacer la transpuesta.

array([[17, 37,  4],
       [13, 93, 40]])

## Como dar la vuelta a un array

In [106]:
matrix = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matrix

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.flip(matrix) #Damos la vuelta a un array.

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [108]:
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
np.flip(matrix) #Damos la vuelta a la matriz.

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [110]:
np.flip(matrix, axis=0) #Damos la vulta solo a las filas.

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [111]:
np.flip(matrix, axis=1) #Damos la vuelta a las columnas.

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [112]:
matrix[1] = np.flip(matrix[1]) #Damos la vuelta a la fila que queremos.
matrix

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [113]:
matrix[:,1] = np.flip(matrix[:,1])
matrix #Damos la vuelta a la columna que queremos.

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

## Reformar y aplanar matrices multidimensionales

In [114]:
matrix = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
matrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
matrix.flatten() #Transformamos una matriz en un array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [116]:
a1 = matrix.flatten() 
a1[0] = 99 #Modificamos el valor del array.
a1 

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [117]:
matrix #Pero no se modifica el valor de la matriz y que flatten crea una copia.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [118]:
a2 = matrix.ravel()
a2[0] = 98
print(matrix)  #Podemos utilizar la función ravel. En este caso, si que se cambia el valor original.
print(a2)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]


© 2008–2022, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
Licensed under the 3-clause BSD License.
https://numpy.org/doc/stable/user/absolute_beginners.html